### ISSUE TITLE
Cannot create Schedule (CDN)

### ISSUE THREAD

**Issue by noho89** [nhn/tui.calendar#410]
I'm experiencing issues with this website:
[](https://www.olehrecords.com/calendar)

It worked perfectly and a few days ago the TUI calendar stopped working. I noticed similar issues with CDN dependencies but I didn't succeed in solving this using the same solutions (e.g using older versions, adding DOM component etc.)
Any idea?

> Uncaught TypeError: this.start.setHours is not a function
    at Schedule../src/js/model/schedule.js.Schedule.setAllDayPeriod (tui-calendar.js:17444)
    at Schedule../src/js/model/schedule.js.Schedule.init (tui-calendar.js:17417)
    at Function../src/js/model/schedule.js.Schedule.create (tui-calendar.js:17372)
    at Base../src/js/controller/base.js.Base.createSchedule (tui-calendar.js:6888)
    at tui-calendar.js:6912
    at tui-code-snippet.js:1062
    at forEachArray (tui-code-snippet.js:947)
    at forEach (tui-code-snippet.js:1024)
    at Object.map (tui-code-snippet.js:1061)
    at Base../src/js/controller/base.js.Base.createSchedules (tui-calendar.js:6911)

**Comment by jungeun-cho** [comment]
@noho89 
Can you write in more detail?
For example, CDN usage code ...

Have you checked the example files?

https://github.com/nhn/tui.calendar/tree/master/examples

**Comment by noho89** [comment]
I did check the example files. My website was working properly until something has changed in the CDN.

This is a Webflow site, so I can't really access the entire code, only add snippets. [This](https://www.olehrecords.com/calendar) is the page and this is how the CDN is added: 

```
<script src="https://uicdn.toast.com/tui.dom/v3.0.0/tui-dom.js"></script>
<script src="https://uicdn.toast.com/tui.time-picker/latest/tui-time-picker.min.js"></script>
<script src="https://uicdn.toast.com/tui.date-picker/latest/tui-date-picker.min.js"></script>
<script src="https://uicdn.toast.com/tui-calendar/latest/tui-calendar.js"></script>
```

Then, a jQuery script is creating objects (which are logged to the console) which are pushed to an array called `events` which is then used in `calendar.createSchedules(events);`

And then I get these two error messages:
```
jquery-3.4.1.min.220afd743d.js:2 jQuery.Deferred exception: this.start.setHours is not a function TypeError: this.start.setHours is not a function
    at Schedule../src/js/model/schedule.js.Schedule.setAllDayPeriod (https://uicdn.toast.com/tui-calendar/latest/tui-calendar.js:17444:16)
    at Schedule../src/js/model/schedule.js.Schedule.init (https://uicdn.toast.com/tui-calendar/latest/tui-calendar.js:17417:14)
    at Function../src/js/model/schedule.js.Schedule.create (https://uicdn.toast.com/tui-calendar/latest/tui-calendar.js:17372:10)
    at Base../src/js/controller/base.js.Base.createSchedule (https://uicdn.toast.com/tui-calendar/latest/tui-calendar.js:6888:42)
    at https://uicdn.toast.com/tui-calendar/latest/tui-calendar.js:6912:21
    at https://uicdn.toast.com/tui.code-snippet/latest/tui-code-snippet.js:1062:36
    at forEachArray (https://uicdn.toast.com/tui.code-snippet/latest/tui-code-snippet.js:947:23)
    at forEach (https://uicdn.toast.com/tui.code-snippet/latest/tui-code-snippet.js:1024:10)
    at Object.map (https://uicdn.toast.com/tui.code-snippet/latest/tui-code-snippet.js:1061:6)
    at Base../src/js/controller/base.js.Base.createSchedules (https://uicdn.toast.com/tui-calendar/latest/tui-calendar.js:6911:17) undefined
```

```
Uncaught TypeError: this.start.setHours is not a function
    at Schedule../src/js/model/schedule.js.Schedule.setAllDayPeriod (tui-calendar.js:17444)
    at Schedule../src/js/model/schedule.js.Schedule.init (tui-calendar.js:17417)
    at Function../src/js/model/schedule.js.Schedule.create (tui-calendar.js:17372)
    at Base../src/js/controller/base.js.Base.createSchedule (tui-calendar.js:6888)
    at tui-calendar.js:6912
    at tui-code-snippet.js:1062
    at forEachArray (tui-code-snippet.js:947)
    at forEach (tui-code-snippet.js:1024)
    at Object.map (tui-code-snippet.js:1061)
    at Base../src/js/controller/base.js.Base.createSchedules (tui-calendar.js:6911)
```

**Comment by jungeun-cho** [comment]
@noho89

The format of the date data (start, end) is incorrect.

YYYY-MM-DD (X)
To pass it as a dateString, you need to include the time information as well.

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date

**Comment by noho89** [comment]
The problem was in the content itself (some events were missing start and end time) and it is now working properly.

> To pass it as a dateString, you need to include the time information as well.
Are you sure about that? I didn't change the format and it is working.

**Comment by jungeun-cho** [comment]
@noho89 
I was mistaken!
I'm glad your problem is solved anyway.
Happy coding 🙂
