### ISSUE TITLE
window ist not defined

### ISSUE THREAD

**Issue by mayrhueli** [nhn/tui.calendar#525]
## Development Environment
Chrome, MacOS, NodeJs

## Current Behavior
I tried to "include" the TUI calender into my WEB Project but is always throws the exception: windoe is not defined when I try to run the Example code

```js
var Calendar = require('tui-calendar'); 
```

Exception: }) (window, function(__WEBPACK_EXTERNAL_MODULE_tui_code_snippet__, __WEBPACK_EXTERNAL_MODULE_tui_date_picker__) {
    ^

this is my first issue ever - so hope I gave enough information
thanks

**Comment by dongsik-yoo** [comment]
#511 might be helpful for you. And check dependency packages of Calendar if you use package manager(npm, yarn)

**Comment by tingll99** [comment]
I'm encountering the same issue and I installed snippets, date_picker and time_picker




## Version


## Development Environment
Chrome, Windows 10, nodeJS

## Current Behavior
`var Calendar = require('tui-calendar');
require("tui-calendar/dist/tui-calendar.css");`

C:\Users\Lyle Tingle\Documents\GitHub\SD-D-Project\node_modules\tui-calendar\dist\tui-calendar.js:16
})(window, function(__WEBPACK_EXTERNAL_MODULE_tui_code_snippet__, __WEBPACK_EXTERNAL_MODULE_tui_date_picker__) {
   ^

ReferenceError: window is not defined
    at Object.<anonymous> (C:\Users\Lyle Tingle\Documents\GitHub\SD-D-Project\node_modules\tui-calendar\dist\tui-calendar.js:16:4)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Module.require (internal/modules/cjs/loader.js:1044:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (C:\Users\Lyle Tingle\Documents\GitHub\SD-D-Project\server.js:5:16)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
```js

**Comment by reinaldoamaralstudio** [comment]
Thanks!

 <https://reinaldoamaral.net/galeria/index.php/home/brasil-central>
 <https://reinaldoamaral.net/galeria/index.php/home/brasil-central>

**Comment by harshith-venkatesh** [comment]
Is there anyone who resolved the above issue?
I am facing this issue in remix

**Comment by adhrinae** [comment]
@harshith-venkatesh 

The calendar does not support SSR yet, so you need to handle browser-only codes by yourself.
There's a documentation about this issue in Remix.

https://remix.run/docs/en/v1/guides/constraints#browser-only-code-on-the-server

**Comment by DeRaowl** [comment]
Hi Team, I found the solution for the above problem. Basically while @toast-ui/react-calendar package, we can name the file as <FILENAME>.client.tsx extension which makes file to render at client end.

**Comment by harshith-venkatesh** [comment]
Thank you @adhrinae @DeRaowl for the help and support 👍

**Comment by innellea** [comment]
just use dynamic import like this:
`const Calendar = dynamic(() => import('../components/Calendar/Calendar'), {
  ssr: false,
})`

**Comment by HouCoder** [comment]
As of today, the dynamic way doesn't work any more with Next.js 13, I got this error when I try to use this package
```
react-server-dom-webpack-client.browser.development.js:1602 Uncaught TypeError: Cannot redefine property: default
    at Function.defineProperty (<anonymous>)
    at eval (webpack-internal:///(:3000/sc_server)/./node_modules/@toast-ui/react-calendar/dist/toastui-react-calendar.mjs:6:8)
```
